/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banksystem.view;

import banksystem.controller.BankSystem;
import banksystem.modal.Client;
import banksystem.modal.PersonalInfo;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author EHAB-
 */
public class ClientPage extends javax.swing.JFrame {

    /**
     * Creates new form ClientPage
     */
    private int count;
    private int ready;
    private BankSystem bankSystem;
    private Client clnt;
    void setPanelEnabled(JPanel panel, Boolean isEnabled) {
        panel.setEnabled(isEnabled);

        Component[] components = panel.getComponents();

        for (Component component : components) {
            component.setVisible(isEnabled);
        }
    }
    public void countDown(JButton b){
        if(count >0 )
            count--;
        if(ready == count)
            b.setEnabled(true);
    }
    public void countUp(JButton b){
        if(count <ready )
            count++;
        if(ready == count)
            b.setEnabled(true);
    }
    public boolean checktypeint(String s){
        try{
            Integer.parseInt(s);
            return true;
        }catch(NumberFormatException e){
           return false; 
        }
    }
    public boolean checktypedouble(String s){
        try{
            Double.parseDouble(s);
            return true;
        }catch(NumberFormatException e){
           return false; 
        }
    }
    public ClientPage(long id) throws SQLException {
        bankSystem = new BankSystem();
        clnt = new Client(id);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JPanel();
        menuButton = new javax.swing.JLabel();
        homePagebutton = new javax.swing.JLabel();
        addAcount = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        heading = new javax.swing.JPanel();
        bankName = new javax.swing.JLabel();
        viewPage = new javax.swing.JPanel();
        homePage = new javax.swing.JPanel();
        graphicPanel = new GraphicPanel();
        personalInfo = new javax.swing.JLabel();
        updateAccount = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        idfield7 = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        idfield9 = new javax.swing.JTextField();
        createburron7 = new javax.swing.JButton();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcom");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenu.setBackground(new java.awt.Color(0, 47, 87));
        mainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuMouseEntered(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(51, 51, 51));
        menuButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menuButton.setForeground(new java.awt.Color(0, 153, 255));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        menuButton.setText(" Main menu");
        menuButton.setFocusTraversalPolicyProvider(true);
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuButtonMousePressed(evt);
            }
        });

        homePagebutton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homePagebutton.setForeground(new java.awt.Color(0, 153, 255));
        homePagebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        homePagebutton.setText(" Home Page");
        homePagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homePagebuttonMousePressed(evt);
            }
        });

        addAcount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addAcount.setForeground(new java.awt.Color(0, 153, 255));
        addAcount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        addAcount.setText(" Transfer Money");
        addAcount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAcountMouseClicked(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(51, 51, 51));
        logoutButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 153, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logouticon2.png"))); // NOI18N
        logoutButton.setText(" Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAcount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homePagebutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homePagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAcount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        getContentPane().add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 730));

        heading.setBackground(new java.awt.Color(51, 51, 51));
        heading.setOpaque(false);

        bankName.setBackground(new java.awt.Color(0, 153, 102));
        bankName.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        bankName.setForeground(new java.awt.Color(0, 153, 255));
        bankName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bankicon.png"))); // NOI18N
        bankName.setText(" Syrian National Bank");

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankName, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 90));

        viewPage.setMaximumSize(new java.awt.Dimension(1020, 730));
        viewPage.setOpaque(false);
        viewPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPageMouseEntered(evt);
            }
        });
        viewPage.setLayout(new java.awt.CardLayout());

        homePage.setForeground(new java.awt.Color(0, 153, 255));
        homePage.setOpaque(false);
        homePage.setPreferredSize(new java.awt.Dimension(1020, 730));
        homePage.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homePageComponentShown(evt);
            }
        });

        graphicPanel.setOpaque(false);

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        personalInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        personalInfo.setForeground(new java.awt.Color(0, 153, 255));
        personalInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/personalicon.png"))); // NOI18N
        personalInfo.setText("  hi manager");

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addComponent(graphicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(personalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addComponent(personalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        viewPage.add(homePage, "card3");

        updateAccount.setMaximumSize(new java.awt.Dimension(1360, 1080));
        updateAccount.setOpaque(false);
        updateAccount.setPreferredSize(new java.awt.Dimension(1360, 1080));
        updateAccount.setRequestFocusEnabled(false);
        updateAccount.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updateAccountComponentShown(evt);
            }
        });

        jLabel119.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(0, 102, 255));
        jLabel119.setText("ID account");

        idfield7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idfield7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfield7FocusLost(evt);
            }
        });

        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchicon.png"))); // NOI18N
        jLabel120.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel120MousePressed(evt);
            }
        });

        jLabel121.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 0, 0));
        jLabel121.setText("was not found");

        jLabel123.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("transfer money");

        jLabel126.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(0, 102, 255));
        jLabel126.setText("Amount of money");

        idfield9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idfield9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfield9FocusLost(evt);
            }
        });
        idfield9.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                idfield9InputMethodTextChanged(evt);
            }
        });

        createburron7.setBackground(new java.awt.Color(0, 47, 87));
        createburron7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        createburron7.setForeground(new java.awt.Color(0, 153, 255));
        createburron7.setText("transfer");
        createburron7.setToolTipText("");
        createburron7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createburron7ActionPerformed(evt);
            }
        });

        jLabel130.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(0, 255, 0));
        jLabel130.setText("Done successfully !!!");
        jLabel130.setToolTipText("");

        jLabel131.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 0, 0));
        jLabel131.setText("Operation Failed !!!");
        jLabel131.setToolTipText("");

        jLabel122.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(255, 255, 255));
        jLabel122.setText("your account :");

        jLabel124.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(255, 0, 0));
        jLabel124.setText("You can not send more than your account");

        javax.swing.GroupLayout updateAccountLayout = new javax.swing.GroupLayout(updateAccount);
        updateAccount.setLayout(updateAccountLayout);
        updateAccountLayout.setHorizontalGroup(
            updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(updateAccountLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createburron7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel131, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel130, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateAccountLayout.createSequentialGroup()
                            .addComponent(jLabel126)
                            .addGap(18, 18, 18)
                            .addComponent(idfield9, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel122, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel124, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateAccountLayout.createSequentialGroup()
                                .addComponent(idfield7, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel120)))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        updateAccountLayout.setVerticalGroup(
            updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAccountLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idfield7)
                    .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel121)
                .addGap(18, 18, 18)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idfield9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel126, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel122)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel124)
                .addGap(16, 16, 16)
                .addComponent(createburron7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel131)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel130)
                .addGap(8, 8, 8)
                .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1075, 1075, 1075))
        );

        viewPage.add(updateAccount, "card2");

        getContentPane().add(viewPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 1020, 730));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 820));

        setSize(new java.awt.Dimension(1244, 827));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMousePressed
        if(mainMenu.getBounds().width == 210 ||mainMenu.getBounds().width == 211){
            Thread t;
            t = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=210;i>70;i--){
                            Thread.sleep(1);
                            mainMenu.setSize(i,730);
                        }
                    }catch(InterruptedException e){}
                }
            };t.start();
        }
        else if(mainMenu.getBounds().width == 70|| mainMenu.getBounds().width == 71){
            Thread t = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=70;i<=210;i++){
                            Thread.sleep(1);
                            mainMenu.setSize(i,730);
                        }
                    }catch(InterruptedException e){}
                }
            };t.start();
        }
    }//GEN-LAST:event_menuButtonMousePressed

    private void homePagebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePagebuttonMousePressed
        setPanelEnabled(viewPage, false);
        homePage.setVisible(true);
    }//GEN-LAST:event_homePagebuttonMousePressed

    private void addAcountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAcountMouseClicked
        // TODO add your handling code here:
        this.setPanelEnabled(viewPage, false);
        updateAccount.setVisible(true);
    }//GEN-LAST:event_addAcountMouseClicked

    private void logoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMousePressed
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_logoutButtonMousePressed

    private void mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseEntered

    }//GEN-LAST:event_mainMenuMouseEntered

    private void homePageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homePageComponentShown
        GraphicPanel.updatePage = true;
        double l =0,d= 0,e=0,f=0;
        /*
        try {
            DBConnect.Connect();
            DBConnect.resultStatment(";");
            if(DBConnect.res.next()){
                l = DBConnect.res.getDouble("lira");
                d = DBConnect.res.getDouble("dollar");
                e = DBConnect.res.getDouble("euro");
                f = DBConnect.res.getDouble("fils");
            }
        } catch (SQLException ex) {
        }*/
    }//GEN-LAST:event_homePageComponentShown

    private void idfield7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfield7FocusLost

    }//GEN-LAST:event_idfield7FocusLost

    private void jLabel120MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel120MousePressed
        try {
            long id = Long.parseLong(idfield7.getText());
            if(PersonalInfo.tableType(id).equals("client")&& PersonalInfo.checkID((int) id)){
                PersonalInfo per = new PersonalInfo(id);
                jLabel121.setForeground(Color.green);
                jLabel121.setText("client ID found");
                jLabel122.setText("Your account is: "+ bankSystem.getMoneyAmount(clnt.getId())+" TL");
                jLabel121.setVisible(true);
                idfield9.setEditable(true);
            }
            else {
                idfield9.setEditable(false);
                jLabel121.setForeground(Color.red);
                jLabel121.setText("client ID not found");
                jLabel121.setVisible(true);
            }
        } catch (SQLException |NumberFormatException ex) {
            jLabel121.setForeground(Color.red);
            jLabel121.setText("please enter valid ID and should be number only");
            jLabel121.setVisible(true);
            idfield9.setEditable(false);
        }
    }//GEN-LAST:event_jLabel120MousePressed

    private void idfield9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfield9FocusLost
        try {
            if(bankSystem.checkMoneyAvilability(clnt.getId(),idfield9.getText()))
                jLabel124.setVisible(false);
            else jLabel124.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ClientPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_idfield9FocusLost

    private void idfield9InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_idfield9InputMethodTextChanged
        try{
            Double.parseDouble(idfield9.getText());
        }catch(Exception ex){
            idfield9.setText("");
        }
    }//GEN-LAST:event_idfield9InputMethodTextChanged

    private void createburron7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createburron7ActionPerformed
        try {
            if(bankSystem.excuteMoneyTransfer(idfield7.getText(),idfield9.getText())){
                jLabel131.setVisible(false);
                jLabel130.setVisible(true);
            }
            else{
                jLabel131.setVisible(true);
                jLabel130.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClientPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_createburron7ActionPerformed

    private void updateAccountComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updateAccountComponentShown
        // TODO add your handling code here:
        jLabel124.setVisible(false);
        jLabel121.setVisible(false);
        jLabel130.setVisible(false);
        jLabel131.setVisible(false);
    }//GEN-LAST:event_updateAccountComponentShown

    private void viewPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPageMouseEntered

    }//GEN-LAST:event_viewPageMouseEntered

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAcount;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bankName;
    private javax.swing.JButton createburron7;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JPanel heading;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel homePagebutton;
    private javax.swing.JTextField idfield7;
    private javax.swing.JTextField idfield9;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel menuButton;
    private javax.swing.JLabel personalInfo;
    private javax.swing.JPanel updateAccount;
    private javax.swing.JPanel viewPage;
    // End of variables declaration//GEN-END:variables

}
