/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banksystem.view;

import banksystem.controller.BankSystem;
import banksystem.modal.Manager;
import banksystem.modal.PersonalInfo;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JPanel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author EHAB-
 */
public class ManagerPage extends javax.swing.JFrame {

    /**
     * Creates new form ManagerPage
     */
    private final Manager manager;
    private final BankSystem bankSystem;
    private int ready;
    private int count;
    void setPanelEnabled(JPanel panel, Boolean isEnabled) {
        panel.setEnabled(isEnabled);

        Component[] components = panel.getComponents();

        for (Component component : components) {
            component.setVisible(isEnabled);
        }
    }
    public void countDown(JButton b){
        if(count >0 )
            count--;
        if(ready == count)
            b.setEnabled(true);
    }
    public void countUp(JButton b){
        if(count <ready )
            count++;
        if(ready == count)
            b.setEnabled(true);
    }
    public boolean checktypeint(String s){
        try{
            Integer.parseInt(s);
            return true;
        }catch(NumberFormatException e){
           return false; 
        }
    }
    public boolean checktypedouble(String s){
        try{
            Double.parseDouble(s);
            return true;
        }catch(NumberFormatException e){
           return false; 
        }
    }
    public ManagerPage() throws SQLException {
        bankSystem = new BankSystem();
        manager = new Manager(1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JPanel();
        menuButton = new javax.swing.JLabel();
        homePagebutton = new javax.swing.JLabel();
        addAcount = new javax.swing.JLabel();
        changeMonyAmount = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        heading = new javax.swing.JPanel();
        bankName = new javax.swing.JLabel();
        viewPage = new javax.swing.JPanel();
        homePage = new javax.swing.JPanel();
        graphicPanel = new GraphicPanel();
        personalInfo = new javax.swing.JLabel();
        creatNewAccount = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        firstnamefield2 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        emailfield2 = new javax.swing.JTextField();
        passwordfield2 = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        createbutton2 = new javax.swing.JButton();
        jLabel96 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        idfield2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deleteAccount = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        idfield5 = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        firstnamefield3 = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        emailfield3 = new javax.swing.JTextField();
        createburron5 = new javax.swing.JButton();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        updateAccount = new javax.swing.JPanel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        createburron6 = new javax.swing.JButton();
        idfield7 = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        idfield8 = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        idfield9 = new javax.swing.JTextField();
        createburron7 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1360, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenu.setBackground(new java.awt.Color(0, 47, 87));
        mainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuMouseEntered(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(51, 51, 51));
        menuButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        menuButton.setForeground(new java.awt.Color(0, 153, 255));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        menuButton.setText(" Main menu");
        menuButton.setFocusTraversalPolicyProvider(true);
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuButtonMousePressed(evt);
            }
        });

        homePagebutton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homePagebutton.setForeground(new java.awt.Color(0, 153, 255));
        homePagebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        homePagebutton.setText(" Home Page");
        homePagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homePagebuttonMousePressed(evt);
            }
        });

        addAcount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addAcount.setForeground(new java.awt.Color(0, 153, 255));
        addAcount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        addAcount.setText(" create new account");
        addAcount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAcountMouseClicked(evt);
            }
        });

        changeMonyAmount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        changeMonyAmount.setForeground(new java.awt.Color(0, 153, 255));
        changeMonyAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuicon.png"))); // NOI18N
        changeMonyAmount.setText(" Accounts Setting");
        changeMonyAmount.setToolTipText("");
        changeMonyAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMonyAmountMouseClicked(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(51, 51, 51));
        logoutButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 153, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logouticon2.png"))); // NOI18N
        logoutButton.setText(" Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAcount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homePagebutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeMonyAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homePagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAcount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeMonyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        getContentPane().add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 730));

        heading.setBackground(new java.awt.Color(51, 51, 51));
        heading.setOpaque(false);

        bankName.setBackground(new java.awt.Color(0, 153, 102));
        bankName.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        bankName.setForeground(new java.awt.Color(0, 153, 255));
        bankName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bankicon.png"))); // NOI18N
        bankName.setText(" Syrian National Bank");

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankName, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 90));

        viewPage.setMaximumSize(new java.awt.Dimension(1020, 730));
        viewPage.setOpaque(false);
        viewPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPageMouseEntered(evt);
            }
        });
        viewPage.setLayout(new java.awt.CardLayout());

        homePage.setForeground(new java.awt.Color(0, 153, 255));
        homePage.setOpaque(false);
        homePage.setPreferredSize(new java.awt.Dimension(1020, 730));
        homePage.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homePageComponentShown(evt);
            }
        });

        graphicPanel.setOpaque(false);

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        personalInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        personalInfo.setForeground(new java.awt.Color(0, 153, 255));
        personalInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/personalicon.png"))); // NOI18N
        personalInfo.setText("  hi manager");

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addComponent(graphicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(personalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addComponent(personalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        viewPage.add(homePage, "card3");

        creatNewAccount.setOpaque(false);
        creatNewAccount.setPreferredSize(new java.awt.Dimension(1020, 730));
        creatNewAccount.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                creatNewAccountComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                creatNewAccountComponentShown(evt);
            }
        });

        jLabel76.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 102, 255));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("creat new account");

        jLabel88.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 102, 255));
        jLabel88.setText("ID account");

        jLabel89.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(0, 102, 255));
        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asteriskicon.png"))); // NOI18N
        jLabel89.setText("name");

        firstnamefield2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firstnamefield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefield2FocusLost(evt);
            }
        });

        jLabel90.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(0, 102, 255));
        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asteriskicon.png"))); // NOI18N
        jLabel90.setText("email");

        emailfield2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfield2FocusLost(evt);
            }
        });

        passwordfield2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfield2FocusLost(evt);
            }
        });

        jLabel93.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(0, 102, 255));
        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asteriskicon.png"))); // NOI18N
        jLabel93.setText("password");

        createbutton2.setBackground(new java.awt.Color(0, 47, 87));
        createbutton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        createbutton2.setForeground(new java.awt.Color(0, 153, 255));
        createbutton2.setText("create");
        createbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbutton2ActionPerformed(evt);
            }
        });

        jLabel96.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 0, 51));
        jLabel96.setText("please enter valid email");
        jLabel96.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel96ComponentShown(evt);
            }
        });

        jLabel98.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 0, 51));
        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asteriskicon.png"))); // NOI18N
        jLabel98.setText("astric mean compulsory");
        jLabel98.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel98ComponentShown(evt);
            }
        });

        jLabel99.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 0, 51));
        jLabel99.setText("please set password");
        jLabel99.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel99ComponentShown(evt);
            }
        });

        jLabel100.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 0, 51));
        jLabel100.setText("please enter first name");
        jLabel100.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel100ComponentShown(evt);
            }
        });

        idfield2.setEditable(false);
        idfield2.setBackground(new java.awt.Color(204, 204, 204));
        idfield2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Done succsessfully !!");

        javax.swing.GroupLayout creatNewAccountLayout = new javax.swing.GroupLayout(creatNewAccount);
        creatNewAccount.setLayout(creatNewAccountLayout);
        creatNewAccountLayout.setHorizontalGroup(
            creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel76, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(creatNewAccountLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatNewAccountLayout.createSequentialGroup()
                        .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel93, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel90, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel88, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordfield2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailfield2)
                            .addComponent(firstnamefield2)
                            .addComponent(jLabel96, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel99, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatNewAccountLayout.createSequentialGroup()
                        .addComponent(jLabel98)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        creatNewAccountLayout.setVerticalGroup(
            creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatNewAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel76)
                .addGap(18, 18, 18)
                .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(idfield2))
                .addGap(18, 18, 18)
                .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamefield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailfield2)
                    .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(jLabel96)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel99)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creatNewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel98))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(385, 385, 385))
        );

        viewPage.add(creatNewAccount, "card2");

        deleteAccount.setOpaque(false);
        deleteAccount.setPreferredSize(new java.awt.Dimension(1020, 730));
        deleteAccount.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deleteAccountComponentShown(evt);
            }
        });

        jLabel105.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(0, 102, 255));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("Delete Account");

        jLabel106.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(0, 102, 255));
        jLabel106.setText("ID account");

        idfield5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idfield5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfield5FocusLost(evt);
            }
        });
        idfield5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfield5ActionPerformed(evt);
            }
        });

        jLabel107.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 102, 255));
        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asteriskicon.png"))); // NOI18N
        jLabel107.setText("first name");

        firstnamefield3.setEditable(false);
        firstnamefield3.setBackground(new java.awt.Color(204, 204, 204));
        firstnamefield3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        firstnamefield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnamefield3FocusLost(evt);
            }
        });

        jLabel108.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(0, 102, 255));
        jLabel108.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asteriskicon.png"))); // NOI18N
        jLabel108.setText("email");

        emailfield3.setEditable(false);
        emailfield3.setBackground(new java.awt.Color(204, 204, 204));
        emailfield3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailfield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfield3FocusLost(evt);
            }
        });
        emailfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfield3ActionPerformed(evt);
            }
        });

        createburron5.setBackground(new java.awt.Color(0, 47, 87));
        createburron5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        createburron5.setForeground(new java.awt.Color(0, 153, 255));
        createburron5.setText("Delete");
        createburron5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createburron5ActionPerformed(evt);
            }
        });

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchicon.png"))); // NOI18N
        jLabel112.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel112MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel112MouseReleased(evt);
            }
        });

        jLabel113.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 0, 51));
        jLabel113.setText("please enter valid id ");
        jLabel113.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel113ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout deleteAccountLayout = new javax.swing.GroupLayout(deleteAccount);
        deleteAccount.setLayout(deleteAccountLayout);
        deleteAccountLayout.setHorizontalGroup(
            deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(deleteAccountLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createburron5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAccountLayout.createSequentialGroup()
                        .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel108, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel107, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(deleteAccountLayout.createSequentialGroup()
                                .addComponent(idfield5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel112))
                            .addComponent(emailfield3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnamefield3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel113, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        deleteAccountLayout.setVerticalGroup(
            deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel105)
                .addGap(18, 18, 18)
                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idfield5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel113)
                .addGap(18, 18, 18)
                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamefield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailfield3)
                    .addComponent(jLabel108, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(createburron5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );

        viewPage.add(deleteAccount, "card2");

        updateAccount.setMaximumSize(new java.awt.Dimension(1360, 1080));
        updateAccount.setOpaque(false);
        updateAccount.setPreferredSize(new java.awt.Dimension(1360, 1080));
        updateAccount.setRequestFocusEnabled(false);
        updateAccount.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updateAccountComponentShown(evt);
            }
        });

        jLabel118.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(0, 102, 255));
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("update Account information");
        jLabel118.setAutoscrolls(true);

        jLabel119.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(0, 102, 255));
        jLabel119.setText("ID account");

        createburron6.setBackground(new java.awt.Color(0, 47, 87));
        createburron6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        createburron6.setForeground(new java.awt.Color(0, 153, 255));
        createburron6.setText("update");
        createburron6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createburron6ActionPerformed(evt);
            }
        });

        idfield7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idfield7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfield7FocusLost(evt);
            }
        });

        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchicon.png"))); // NOI18N
        jLabel120.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel120MousePressed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "name", "email", "password" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel121.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 0, 0));
        jLabel121.setText("was not found");

        jLabel122.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(0, 102, 255));
        jLabel122.setText("chose one");

        jLabel123.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(0, 102, 255));

        idfield8.setEditable(false);
        idfield8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idfield8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfield8FocusLost(evt);
            }
        });
        idfield8.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                idfield8InputMethodTextChanged(evt);
            }
        });
        idfield8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfield8ActionPerformed(evt);
            }
        });

        jLabel124.setBackground(new java.awt.Color(255, 255, 255));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editableicon.png"))); // NOI18N
        jLabel124.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel124MousePressed(evt);
            }
        });
        jLabel124.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel124InputMethodTextChanged(evt);
            }
        });

        jLabel125.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(255, 0, 0));
        jLabel125.setText("was not found");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("upload money");

        jLabel126.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(0, 102, 255));
        jLabel126.setText("Amount of money");

        idfield9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idfield9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfield9FocusLost(evt);
            }
        });
        idfield9.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                idfield9InputMethodTextChanged(evt);
            }
        });
        idfield9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfield9ActionPerformed(evt);
            }
        });

        createburron7.setBackground(new java.awt.Color(0, 47, 87));
        createburron7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        createburron7.setForeground(new java.awt.Color(0, 153, 255));
        createburron7.setText("upload");
        createburron7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createburron7ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("add");
        jRadioButton1.setToolTipText("");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("subtract");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel128.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 0, 0));
        jLabel128.setText("Operation Failed !!!");
        jLabel128.setToolTipText("");

        jLabel129.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(0, 255, 0));
        jLabel129.setText("Done successfully !!!");
        jLabel129.setToolTipText("");

        jLabel130.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(0, 255, 0));
        jLabel130.setText("Done successfully !!!");
        jLabel130.setToolTipText("");

        jLabel131.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 0, 0));
        jLabel131.setText("Operation Failed !!!");
        jLabel131.setToolTipText("");

        javax.swing.GroupLayout updateAccountLayout = new javax.swing.GroupLayout(updateAccount);
        updateAccount.setLayout(updateAccountLayout);
        updateAccountLayout.setHorizontalGroup(
            updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel118, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(updateAccountLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel122, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateAccountLayout.createSequentialGroup()
                                .addComponent(idfield7, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel120))
                            .addGroup(updateAccountLayout.createSequentialGroup()
                                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idfield8, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                        .addComponent(jLabel125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(updateAccountLayout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(createburron6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel128, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel129, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel124))))
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel126)
                        .addGap(18, 18, 18)
                        .addComponent(idfield9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateAccountLayout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createburron7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel131, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel130, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(327, 327, 327))
        );
        updateAccountLayout.setVerticalGroup(
            updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAccountLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel119, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idfield7)
                    .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel121)
                .addGap(87, 87, 87)
                .addComponent(jLabel118)
                .addGap(18, 18, 18)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel122, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idfield8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel124, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel125))
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel123, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(createburron6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel128)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel129)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(updateAccountLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(updateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idfield9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel126, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27)
                .addComponent(createburron7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel131)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel130)
                .addGap(699, 699, 699))
        );

        viewPage.add(updateAccount, "card2");

        getContentPane().add(viewPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 1020, 730));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 820));

        setSize(new java.awt.Dimension(1245, 829));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMousePressed
        if(mainMenu.getBounds().width == 210 ||mainMenu.getBounds().width == 211){
            Thread t;
            t = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=210;i>70;i--){
                            Thread.sleep(1);
                            mainMenu.setSize(i,730);
                        }
                    }catch(InterruptedException e){}
                }
            };t.start();
        }
        else if(mainMenu.getBounds().width == 70|| mainMenu.getBounds().width == 71){
            Thread t = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=70;i<=210;i++){
                            Thread.sleep(1);
                            mainMenu.setSize(i,730);
                        }
                    }catch(InterruptedException e){}
                }
            };t.start();
        }
    }//GEN-LAST:event_menuButtonMousePressed

    private void homePagebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePagebuttonMousePressed
        setPanelEnabled(viewPage, false);
        homePage.setVisible(true);
    }//GEN-LAST:event_homePagebuttonMousePressed

    private void logoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMousePressed
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_logoutButtonMousePressed

    private void mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseEntered

    }//GEN-LAST:event_mainMenuMouseEntered

    private void homePageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homePageComponentShown
        GraphicPanel.updatePage = true;
        double l =0,d= 0,e=0,f=0;
        /*
        try {
            DBConnect.Connect();
            DBConnect.resultStatment(";");
            if(DBConnect.res.next()){
                l = DBConnect.res.getDouble("lira");
                d = DBConnect.res.getDouble("dollar");
                e = DBConnect.res.getDouble("euro");
                f = DBConnect.res.getDouble("fils");
            }
        } catch (SQLException ex) {
        }*/
    }//GEN-LAST:event_homePageComponentShown

    private void firstnamefield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield2FocusLost
        if(firstnamefield2.getText().equals(""))
            jLabel100.setVisible(true);
        else jLabel100.setVisible(false);
    }//GEN-LAST:event_firstnamefield2FocusLost

    private void emailfield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfield2FocusLost
        if(emailfield2.getText().equals(""))
        jLabel96.setVisible(true);
        else jLabel96.setVisible(false);
    }//GEN-LAST:event_emailfield2FocusLost

    private void passwordfield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield2FocusLost
        if(passwordfield2.getText().equals(""))
        jLabel99.setVisible(true);
        else jLabel99.setVisible(false);
    }//GEN-LAST:event_passwordfield2FocusLost

    private void createbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbutton2ActionPerformed
        if(jLabel100.isVisible()||jLabel99.isVisible()||jLabel96.isVisible())
            createbutton2.enableInputMethods(false);
        else manager.addNewClient(firstnamefield2.getText(), emailfield2.getText(), passwordfield2.getText());
        jLabel1.setVisible(true);
    }//GEN-LAST:event_createbutton2ActionPerformed

    private void jLabel96ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel96ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel96ComponentShown

    private void jLabel98ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel98ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel98ComponentShown

    private void jLabel99ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel99ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel99ComponentShown

    private void jLabel100ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel100ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel100ComponentShown

    private void creatNewAccountComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_creatNewAccountComponentShown
        long idclient = PersonalInfo.generateID("client");
        idfield2.setText(String.valueOf(idclient));
    }//GEN-LAST:event_creatNewAccountComponentShown

    private void createburron6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createburron6ActionPerformed
        if(jLabel121.getForeground().equals(Color.red)){
            jLabel128.setVisible(true);
            jLabel129.setVisible(false);
            return;
        }           
        try {
            PersonalInfo per = new PersonalInfo(Integer.parseInt(idfield7.getText()));
            switch(jLabel123.getText()){
                case "name" -> {
                    if(idfield8.getText().equals("")){
                        jLabel125.setText("name must not be empty");
                        jLabel125.setVisible(true);
                    }
                    else {
                        jLabel125.setVisible(false);
                        per.setname(idfield8.getText()) ;
                    }
                }
                case "email" -> {
                    if(idfield8.getText().equals("")){
                        jLabel125.setText("email must not be empty");
                        jLabel125.setVisible(true);
                    }
                    else {
                        jLabel125.setVisible(false);
                        per.setEmail(idfield8.getText());
                    }
                }
                case "password" -> {
                    if(idfield8.getText().equals("")){
                        jLabel125.setText("password must not be empty");
                        jLabel125.setVisible(true);
                    }
                    else {
                        jLabel125.setVisible(false);
                        per.setPassword(idfield8.getText(), idfield8.getText());
                    }
                }
                default -> {
                    return ;
                }
            }
            int i = JOptionPane.showOptionDialog(updateAccount, "Are you Sure?", "Confierm Message",JOptionPane.YES_NO_OPTION , 1, null, null, EXIT_ON_CLOSE);
            if(i == JOptionPane.YES_OPTION){
                if(bankSystem.excuteAccountChange(per)){
                    jLabel129.setVisible(true);
                    jLabel128.setVisible(false);
                    JOptionPane.showMessageDialog(updateAccount, "Done successfully");
                }
                else {
                    jLabel129.setVisible(false);
                    jLabel128.setVisible(true);
                    JOptionPane.showMessageDialog(updateAccount, "failed");
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.getLocalizedMessage());
            System.out.println("here");
        }
    }//GEN-LAST:event_createburron6ActionPerformed

    private void idfield7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfield7FocusLost
        try {
            int id = Integer.parseInt(idfield7.getText());
            if(PersonalInfo.tableType(id).equals("client")){
                if(PersonalInfo.checkID(id)){
                    jLabel121.setVisible(true);
                    jComboBox3.setEditable(false);
                    jLabel121.setForeground(Color.red);
                    jLabel121.setText("client ID not found");
                }
                PersonalInfo per = new PersonalInfo(id);
                jLabel121.setVisible(false);
                jComboBox3.setEditable(true);
                createburron6.setEnabled(true);

            }
            else {
                createburron6.setEnabled(false);
                jLabel121.setVisible(true);
                jComboBox3.setEditable(false);
                jLabel121.setForeground(Color.red);
                jLabel121.setText("client ID not found");
            }
        } catch (SQLException |NumberFormatException ex) {
            jLabel121.setForeground(Color.red);
            jLabel121.setText("please enter valid ID and should be number only");
            jLabel121.setVisible(true);
            jComboBox3.setEditable(false);
        }
    }//GEN-LAST:event_idfield7FocusLost

    private void jLabel120MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel120MousePressed
        try {
            long id = Long.parseLong(idfield7.getText());
            if(PersonalInfo.tableType(id).equals("client")&&PersonalInfo.checkID((int) id)){
                PersonalInfo per = new PersonalInfo(id);
                jLabel121.setForeground(Color.green);
                jLabel121.setText("client ID found");
                jLabel121.setVisible(true);
                jComboBox3.setEditable(true);
            }
            else {
                jComboBox3.setEditable(false);
                jLabel121.setForeground(Color.red);
                jLabel121.setText("client ID not found");
                jLabel121.setVisible(true);
            }
        } catch (SQLException |NumberFormatException ex) {
            jLabel121.setForeground(Color.red);
            jLabel121.setText("please enter valid ID and should be number only");
            jLabel121.setVisible(true);
            jComboBox3.setEditable(false);
        }
    }//GEN-LAST:event_jLabel120MousePressed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(jComboBox3.isEditable()){
            try {
                PersonalInfo per = new PersonalInfo(Long.parseLong(idfield7.getText()));
                switch(jComboBox3.getSelectedIndex()){

                    case 1 -> {
                        jLabel123.setText("name");
                        idfield8.setText(per.getname());
                    }
                    case 2 -> {
                        jLabel123.setText("email");idfield8.setText(per.getEmail());
                    }
                    case 3 -> {
                        jLabel123.setText("password");idfield8.setText(per.getPassword());
                    }
                    default -> {
                        return ;
                    }
                }
                idfield8.setEditable(false);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void idfield8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfield8FocusLost
        switch(jLabel123.getText()){
            case "name" -> {
                if(idfield8.getText().equals("")){jLabel125.setText("name must not be empty");jLabel125.setVisible(true);}else jLabel125.setVisible(false);
            }
            case "email" -> {
                if(idfield8.getText().equals("")){jLabel125.setText("email must not be empty");jLabel125.setVisible(true);}else jLabel125.setVisible(false);
            }
            case "password" -> {
                if(idfield8.getText().equals("")){jLabel125.setText("password must not be empty");jLabel125.setVisible(true);}else jLabel125.setVisible(false);
            }
        }
    }//GEN-LAST:event_idfield8FocusLost

    private void idfield8InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_idfield8InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_idfield8InputMethodTextChanged

    private void idfield8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfield8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfield8ActionPerformed

    private void jLabel124MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel124MousePressed
        if(jComboBox3.getSelectedIndex()!= 0)
            idfield8.setEditable(true);
        else idfield8.setEditable(false);
    }//GEN-LAST:event_jLabel124MousePressed

    private void jLabel124InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel124InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel124InputMethodTextChanged

    private void updateAccountComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updateAccountComponentShown
        // TODO add your handling code here:
        jLabel121.setVisible(false);
        jLabel125.setVisible(false);
        jLabel128.setVisible(false);
        jLabel129.setVisible(false);
        jLabel130.setVisible(false);
        jLabel131.setVisible(false);
        jRadioButton1.setSelected(true);
    }//GEN-LAST:event_updateAccountComponentShown

    private void viewPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPageMouseEntered

    }//GEN-LAST:event_viewPageMouseEntered

    private void deleteAccountComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteAccountComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAccountComponentShown

    private void jLabel113ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel113ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel113ComponentShown

    private void jLabel112MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel112MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel112MouseReleased

    private void jLabel112MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel112MousePressed
        try {
            PersonalInfo per = new PersonalInfo(Integer.parseInt(idfield5.getText()));
            if(!PersonalInfo.tableType(per.getId()).equals("client")){
                jLabel113.setVisible(true);
                jLabel113.setText("client ID not found");
                return;
            }
            firstnamefield3.setText(per.getname());
            emailfield3.setText(per.getEmail());
            jLabel113.setVisible(false);
        } catch (SQLException |NumberFormatException ex) {
            jLabel113.setText("please enter valid ID and should be number only");
            jLabel113.setVisible(true);
        }
    }//GEN-LAST:event_jLabel112MousePressed

    private void createburron5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createburron5ActionPerformed
        try {
            PersonalInfo per = new PersonalInfo(Integer.parseInt(idfield5.getText()));
            if(!PersonalInfo.tableType(per.getId()).equals("client")){
                jLabel113.setVisible(true);
                jLabel113.setText("client ID not found");
                return;
            }
            int res = JOptionPane.showOptionDialog(deleteAccount, "Are you Sure?", "Confierm Message",JOptionPane.YES_NO_OPTION , 1, null, null, EXIT_ON_CLOSE);
            if(res == JOptionPane.YES_OPTION){
                firstnamefield3.setText("");
                emailfield3.setText("");
                jLabel113.setVisible(false);
            }
        } catch (SQLException |NumberFormatException ex) {
            jLabel113.setText("please enter valid ID and should be number only"+ex);
            jLabel113.setVisible(true);
        }
    }//GEN-LAST:event_createburron5ActionPerformed

    private void emailfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfield3ActionPerformed

    private void emailfield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfield3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfield3FocusLost

    private void firstnamefield3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnamefield3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield3FocusLost

    private void idfield5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfield5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfield5ActionPerformed

    private void idfield5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfield5FocusLost

    }//GEN-LAST:event_idfield5FocusLost

    private void addAcountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAcountMouseClicked
        // TODO add your handling code here:
        this.setPanelEnabled(viewPage, false);
        creatNewAccount.setVisible(true);
        jLabel1.setVisible(false);
        jLabel96.setVisible(false);
        jLabel100.setVisible(false);
        jLabel99.setVisible(false);
    }//GEN-LAST:event_addAcountMouseClicked

    private void changeMonyAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMonyAmountMouseClicked
        // TODO add your handling code here:
        this.setPanelEnabled(viewPage, false);
        updateAccount.setVisible(true);
    }//GEN-LAST:event_changeMonyAmountMouseClicked

    private void creatNewAccountComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_creatNewAccountComponentHidden
        // TODO add your handling code here:
        long idclient = PersonalInfo.generateID("client");
        idfield2.setText(String.valueOf(idclient));
        firstnamefield2.setText("");
        emailfield2.setText("");
        passwordfield2.setText("");
    }//GEN-LAST:event_creatNewAccountComponentHidden

    private void idfield9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfield9FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idfield9FocusLost

    private void idfield9InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_idfield9InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_idfield9InputMethodTextChanged

    private void idfield9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfield9ActionPerformed
        if(bankSystem.checkMoney(idfield9.getText()))
            jLabel131.setVisible(true);
            jLabel130.setVisible(false);
            
    }//GEN-LAST:event_idfield9ActionPerformed

    private void createburron7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createburron7ActionPerformed
        // TODO add your handling code here:
        long id=0;
        if(jLabel121.isVisible() && !idfield9.getText().equals("")){
            id = Long.parseLong(idfield7.getText());
            jLabel130.setVisible(true);
            jLabel131.setVisible(false);
        }
        else {
            jLabel130.setVisible(false);
            jLabel131.setVisible(true);
            return;
        }
        try {
            if(jRadioButton1.isSelected())
                bankSystem.excuteMoneyChange(idfield9.getText(),id,false);
            else bankSystem.excuteMoneyChange(idfield9.getText(),id,true);
        }catch (SQLException ex) {
            Logger.getLogger(ManagerPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createburron7ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAcount;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bankName;
    private javax.swing.JLabel changeMonyAmount;
    private javax.swing.JPanel creatNewAccount;
    private javax.swing.JButton createburron5;
    private javax.swing.JButton createburron6;
    private javax.swing.JButton createburron7;
    private javax.swing.JButton createbutton2;
    private javax.swing.JPanel deleteAccount;
    private javax.swing.JTextField emailfield2;
    private javax.swing.JTextField emailfield3;
    private javax.swing.JTextField firstnamefield2;
    private javax.swing.JTextField firstnamefield3;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JPanel heading;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel homePagebutton;
    private javax.swing.JTextField idfield2;
    private javax.swing.JTextField idfield5;
    private javax.swing.JTextField idfield7;
    private javax.swing.JTextField idfield8;
    private javax.swing.JTextField idfield9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel menuButton;
    private javax.swing.JTextField passwordfield2;
    private javax.swing.JLabel personalInfo;
    private javax.swing.JPanel updateAccount;
    private javax.swing.JPanel viewPage;
    // End of variables declaration//GEN-END:variables
}
